name: chiral_gnn
channels:
  - rdkit
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - alembic=1.4.3=pyh9f0ad1d_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.11.8=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.11.8=py37h89c1867_0
  - cliff=3.5.0=pyhd8ed1ab_0
  - cmaes=0.7.0=pyhac0dd68_0
  - cmd2=0.9.22=py37hc8dfbb8_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=4.6.2=py37h89c1867_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.66.1=h92f7085_0
  - icu=58.2=he6710b0_3
  - importlib-metadata=3.1.1=pyhd8ed1ab_0
  - importlib_metadata=3.1.1=hd8ed1ab_0
  - intel-openmp=2020.2=254
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - mako=1.1.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py37hb5d75c8_2
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py37hff7bd54_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - optuna=2.3.0=pyhd8ed1ab_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py37he6710b0_0
  - pbr=5.5.1=pyh9f0ad1d_0
  - pcre=8.44=he6710b0_0
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - prettytable=2.0.0=pyhd8ed1ab_0
  - py-boost=1.67.0=py37h04863e7_4
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyperclip=1.8.0=pyh9f0ad1d_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.7.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.4=pyhd3eb1b0_0
  - pyyaml=5.3.1=py37hb5d75c8_1
  - rdkit=2020.03.2.0=py37hc20afe1_1
  - readline=8.0=h7b6447c_0
  - scikit-learn=0.23.2=py37h0573a6f_0
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py37h06a4308_0
  - sqlalchemy=1.3.20=py37h8f50634_0
  - sqlite=3.33.0=h62c20be_0
  - stevedore=3.3.0=py37h89c1867_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.7.0=py37
  - torchvision=0.8.1=py37_cu102
  - tqdm=4.54.0=pyhd8ed1ab_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.35.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
